.TH  imgtool 1
.SH NAME
 imgtool - JPEG photo tool
.SH DESCRIPTION
Imgtool JPEG Photo tool

Renames, reorients, resizes and/or timestamps jpg files with a unique name based on EXIF tags embedded in 
the image files. File naming can be very complex using a variety of EXIF tags. When no options are specified, the tool will set the modification time of the image file to that of the EXIF DateTaken tag. In the absense of this tag the file is left untouched. 

.SH WARNING
This tool is ALPHA. I have tested it in a limited environment and was written to work with my photographs. It may even be destructive. Backing up data is always a good idea before employing automatic tools that can recurse directories. If you break something, you own the remaining pieces.

.SH SYNOPSIS
imgtool [-h] [-a ROTANGLE] [-R] [-c] [-D] [-d directory]
                  [-f format-string] [-i] [-n] [-p Pattern] [-q REQUIRED_TAG]
                  [-r] [-t] [--thumb-dir directory]
                  [--thumb-geometry geometry] [-v] [-V] [-z geometry]
                  [--debug] [--dumpkeys] [--help-geometry] [--help-format]
                  [PATH [PATH ...]]



 [-h] [-R] [-c] [-d directory] [-D] [-f format] [-n] [-p pattern] [-r] [-z geometry] [--help-geometry] [-v] [-V] [--dumpkeys] [PATH [PATH ...]]

.SH General Options
.IP -d|--directory
When renaming, files are moved or copied to the destination directoy maintain their directory tree when recursive. Formatting of ExifTags is allowed. See formatting below. 
.IP -D|--dry-run
Show all actions to be performed without doing them. Also sets -v|--verbose
.IP -i|--ignore-no-exif
Ignore that a file has no EXIF data. Default is to skip files without EXIF data.
.IP -n|--no-clobber
Do not destroy existing destination file. Files will be named as "newname (n).ext" where n is a number indicating the number of files with the new name. Similar to other file renaming operations
.IP -p|--patern
Glob format pattern to search for files, e.g., *.jpg, default is *.[Jj][Pp][Gg]
(see glob(3) and fnmatch(3))
.IP -R|--recurse
Recurse into subdirectories
.IP -v|--verbose
Set verbose mode: Show operations as they are performed. If -d|--dry-run is also set, operations are shown without actually doing them.
.IP -V|--version
Show program version and exit.
.IP --dumpkeys
Dump the EXIF Tag Keys from first found file and exit.

.SH Naming Options
This tool can use the EXIF header data to create a name for the image based on various tags. A detailed description of formatting is below.

.IP -c|--camera-names
Use embedded EXIF camera name to rename files
.IP -f|--format 
Time format string for filenaming in Python strftime format. Default is '@Exif.Image.Model[1]_%Y%m%d%H%M%S@File.ext'

.SH Transformation Options
Images can be resized and rotated. Resizing is to be done based on the geometry specific and rotation is done based on the EXIF header's rotation tags to correct image orientation.

.IP -a|--rotation-angle
Specify the rotation angle, in degrees to reorient images.
.IP -r|--auto-rotate
Automatically rotate image(s) based on EXIF Orientation tag. If not present, or set to 1 no rotation is performed
.IP -z|--resize  geometry
Resize image(s) based on geometry. 

.SH Thumbnail Options
Thumbnails can be generated for each image. They are stored as .PNG files where any rectangular image's padding is done as a transparent alpha channel. 

.IP -t|--thumbnail
Automatically generate PNG thumbnails for each image found. Default geometry is 96x96.
.IP --thumb-dir
Specify the output directory for thumbnails to be written
.IP --thumb-geometry
Specify geometry for the thumbnails created. Percentages can be used but are not recommende.

.SH Help Options
.IP -h|--help
Show help text.
.IP --help-geometry
Show help on resize geometry.
.IP --help-format
Show help on automatic renaming format.

.SH Order of operations
Each image processed, if the operations are specified, has their operations peformed in this order:
.IP
Image resize
.IP
Auto-rotation
.IP
Dating and/or Renaming
.IP
Thumbnail generation

.SH Geometry Specifications
Geometry can be specified as a percentage of the overall image or as a pair of [width]x[height]. 
Width and height are specified in pixels. If width is specified but no height, e.g., 1000x
the image will be reized to a width of 1000px with a height calculated in relation to width to
maintain the image aspect ratio. Conversely, height is specified without a width, e.g., x1000
will resize the image to 1000px high with a width calculated to maintain the aspect ratio. 
When the width and height are spcecified no attempt to maintain the aspect ratio is made.

.SH Format options for filenames

Formatting filenames for automatic renaming is as follows:
    [@|+]type.Tag%timefmt

Tags starting with @ have their spaces replaced with periods (.), Tags starting with + 
do not have spaces replaced. There are two types of tags, File and Exif. File Tags are:

    File.Name:  Filename of the image without extension
    File.Ext:   Extension of filename, e.g., .JPG 
    File.ext:   Extension of filename converted to lower-case, e.g., .jpg
    File.Fullname: Full name of file with directories.
    File.mtime: String representation YYYYMMDDhhmmss of the file's timestamp in the filesystem.


EXIF Tags vary by image and camera. The program exiftool may be useful in finding appropriate tags. 
When specifying EXIF Tags, they are formatted as Exif.Image.Model which results in a string, for one 
of my cameras, as 'NIKON D3400', by default the resultant string will have spaced replaced with 
periods (.), to suppress this behavior, precede them with a plus (+). E.g.:

    @Exif.Image.Make returns 'NIKON.D3400' where +Exif.Image.Make returns 'NIKON D3400' 

This conversion is done just before substituting the tag with its value. 

### Splitting strings in tags
Splitting the tag values can be done as an index of space separated words or as a substring. 

.SH Indexing
To use an index, 
place the index number in brackets, e.g, @Exif.Image.Make[1] returns 'D3400' instead of 'NIKON D3400'. 
Index values start with 0. 

.SH Substrings
To use a substring, place the start and, optionally the length in parentheses. E.g,
@Exif.Image.Make(7,5) will return 'D3400' instead of 'NIKON D3400'. If the second value is omitted the 
length of the value, starting at the first number is presumed, so @Exif.Image.Make(7) will also result 
with 'D3400'

Any EXIF Tag present in the image EXIF header can be used to create all or part of a file name. For example, 
@Image.Make[1]_@File.name@File.ext will create, from DSC_328.JPG a name of 'D3400_DSC_328.jpg'.`


Note that the @File tags are never evaluated with a plus instead of an at-sign, and no indexing or substring
operations are performed.

.SH AUTHOR
Nicole Stevens (https://github.com/nicciniamh)
.SH Copyright
Copyright 2018 Nicole Stevens
.SH License
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

