#!/bin/bash
echo "Building readme-markdown"
echo -e "## Usage\n" >options
echo '```' >>options
../imgtool -h | grep '\[' | grep -v '@'>>options
echo '```'>>options
../imgtool -h | grep '^[ ]*-' | sort | grep -v '-help' | ./splitopts >> options
(for f in $(cat sections) ; do
    t=$(head -1 "$f")
    echo "Adding ${t}" >&2
    cat "$f"
    echo
done) >bot-readme
echo -e '## Table of Contents\n' >toc
./buildtoc bot-readme 2 >>toc
cat head toc bot-readme >readme-markdown.md
cat head bot-readme | pandoc -f markdown --standalone --to man  -o imgtool.1
cat readme-markdown.md | sed -e 's/%/#/g' -e 's/(1)//g' -e 's/|//g' >../README.md
cat readme-markdown.md | sed -e 's/%/#/g' -e 's/(1)//g' -e 's/|//g' | pandoc -f markdown --to html -o ../imgtool.html
cp imgtool.1 ..
rm -f toc options sec-content bot-readme